In [68]:
#numpy学习

In [69]:
#numoy array
import numpy as np
#创建数组
np.array([[1,2,3],[4,5,6],[7,8,9]])
np.arange(10)
np.arange(1,10)
np.linspace(start=1,stop=100,num=50)
np.linspace(1,100,50).reshape(5,10)
np.linspace(0,100,10).reshape(2,5).flatten()
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
#判断条件
a > 5
np.ones(10).reshape(2,5)
np.zeros(10).reshape(2,5)
np.eye(10)
#随机数
np.random.rand(10)
np.random.random((3,4))
np.random.randint(1,10,(3,4))
np.copy(a)
a[1]
a[1][2]
b = np.random.randint(1,10,(5,5))
np.unique(b)
print(b)
#转置矩阵
print(b.T)
#逆矩阵
np.linalg.inv(b)
c = np.eye(5)
#叉乘和点乘
np.dot(b,c)
b * c
#索引
b[1:3,2:4]
b[1,2]
b[b>2]
np.array([1,2,0,True,np.NaN,"hello world"])





[[4 8 1 9 3]
 [7 7 7 6 5]
 [5 6 8 6 9]
 [8 3 9 3 9]
 [7 9 4 5 6]]
[[4 7 5 8 7]
 [8 7 6 3 9]
 [1 7 8 9 4]
 [9 6 6 3 5]
 [3 5 9 9 6]]


array(['1', '2', '0', 'True', 'nan', 'ahhsha'], dtype='<U32')